<?php
/**
 * VoucherSendMethodApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sample API
 *
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * VoucherSendMethodApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VoucherSendMethodApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'checkStatusZNS' => [
            'application/json',
        ],
        'sendVoucherByEmail' => [
            'application/json',
        ],
        'sendVoucherBySMS' => [
            'application/json',
        ],
        'sendVoucherByZNS' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation checkStatusZNS
     *
     * Check status zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTCHECKSTATUSZNS|null $requestcheckstatuszns requestcheckstatuszns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkStatusZNS'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR
     */
    public function checkStatusZNS($x_gi_authorization, $requestcheckstatuszns = null, string $contentType = self::contentTypes['checkStatusZNS'][0])
    {
        list($response) = $this->checkStatusZNSWithHttpInfo($x_gi_authorization, $requestcheckstatuszns, $contentType);
        return $response;
    }

    /**
     * Operation checkStatusZNSWithHttpInfo
     *
     * Check status zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTCHECKSTATUSZNS|null $requestcheckstatuszns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkStatusZNS'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkStatusZNSWithHttpInfo($x_gi_authorization, $requestcheckstatuszns = null, string $contentType = self::contentTypes['checkStatusZNS'][0])
    {
        $request = $this->checkStatusZNSRequest($x_gi_authorization, $requestcheckstatuszns, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\HTTPBADREQUEST' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPBADREQUEST' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPBADREQUEST', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPUNAUTHORIZED', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\HTTPNOTFOUND' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPNOTFOUND' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPNOTFOUND', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPBADREQUEST',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPUNAUTHORIZED',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPNOTFOUND',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation checkStatusZNSAsync
     *
     * Check status zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTCHECKSTATUSZNS|null $requestcheckstatuszns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkStatusZNS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkStatusZNSAsync($x_gi_authorization, $requestcheckstatuszns = null, string $contentType = self::contentTypes['checkStatusZNS'][0])
    {
        return $this->checkStatusZNSAsyncWithHttpInfo($x_gi_authorization, $requestcheckstatuszns, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkStatusZNSAsyncWithHttpInfo
     *
     * Check status zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTCHECKSTATUSZNS|null $requestcheckstatuszns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkStatusZNS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkStatusZNSAsyncWithHttpInfo($x_gi_authorization, $requestcheckstatuszns = null, string $contentType = self::contentTypes['checkStatusZNS'][0])
    {
        $returnType = '\OpenAPI\Client\Model\VOUCHERCHECKZNSRESPONSE';
        $request = $this->checkStatusZNSRequest($x_gi_authorization, $requestcheckstatuszns, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'checkStatusZNS'
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTCHECKSTATUSZNS|null $requestcheckstatuszns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkStatusZNS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function checkStatusZNSRequest($x_gi_authorization, $requestcheckstatuszns = null, string $contentType = self::contentTypes['checkStatusZNS'][0])
    {

        // verify the required parameter 'x_gi_authorization' is set
        if ($x_gi_authorization === null || (is_array($x_gi_authorization) && count($x_gi_authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_gi_authorization when calling checkStatusZNS'
            );
        }



        $resourcePath = '/api/v4.0/vouchers/send/zns/check';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_gi_authorization !== null) {
            $headerParams['X-GI-Authorization'] = ObjectSerializer::toHeaderValue($x_gi_authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($requestcheckstatuszns)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($requestcheckstatuszns));
            } else {
                $httpBody = $requestcheckstatuszns;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendVoucherByEmail
     *
     * Send voucher by mail
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYEMAIL|null $requestsendvoucherbyemail requestsendvoucherbyemail (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByEmail'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR
     */
    public function sendVoucherByEmail($x_gi_authorization, $requestsendvoucherbyemail = null, string $contentType = self::contentTypes['sendVoucherByEmail'][0])
    {
        list($response) = $this->sendVoucherByEmailWithHttpInfo($x_gi_authorization, $requestsendvoucherbyemail, $contentType);
        return $response;
    }

    /**
     * Operation sendVoucherByEmailWithHttpInfo
     *
     * Send voucher by mail
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYEMAIL|null $requestsendvoucherbyemail (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByEmail'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendVoucherByEmailWithHttpInfo($x_gi_authorization, $requestsendvoucherbyemail = null, string $contentType = self::contentTypes['sendVoucherByEmail'][0])
    {
        $request = $this->sendVoucherByEmailRequest($x_gi_authorization, $requestsendvoucherbyemail, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\HTTPBADREQUEST' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPBADREQUEST' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPBADREQUEST', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPUNAUTHORIZED', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\HTTPNOTFOUND' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPNOTFOUND' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPNOTFOUND', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPBADREQUEST',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPUNAUTHORIZED',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPNOTFOUND',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendVoucherByEmailAsync
     *
     * Send voucher by mail
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYEMAIL|null $requestsendvoucherbyemail (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoucherByEmailAsync($x_gi_authorization, $requestsendvoucherbyemail = null, string $contentType = self::contentTypes['sendVoucherByEmail'][0])
    {
        return $this->sendVoucherByEmailAsyncWithHttpInfo($x_gi_authorization, $requestsendvoucherbyemail, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendVoucherByEmailAsyncWithHttpInfo
     *
     * Send voucher by mail
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYEMAIL|null $requestsendvoucherbyemail (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoucherByEmailAsyncWithHttpInfo($x_gi_authorization, $requestsendvoucherbyemail = null, string $contentType = self::contentTypes['sendVoucherByEmail'][0])
    {
        $returnType = '\OpenAPI\Client\Model\VOUCHERSENDEMAILRESPONSE';
        $request = $this->sendVoucherByEmailRequest($x_gi_authorization, $requestsendvoucherbyemail, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendVoucherByEmail'
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYEMAIL|null $requestsendvoucherbyemail (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendVoucherByEmailRequest($x_gi_authorization, $requestsendvoucherbyemail = null, string $contentType = self::contentTypes['sendVoucherByEmail'][0])
    {

        // verify the required parameter 'x_gi_authorization' is set
        if ($x_gi_authorization === null || (is_array($x_gi_authorization) && count($x_gi_authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_gi_authorization when calling sendVoucherByEmail'
            );
        }



        $resourcePath = '/api/v4.0/vouchers/send/email';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_gi_authorization !== null) {
            $headerParams['X-GI-Authorization'] = ObjectSerializer::toHeaderValue($x_gi_authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($requestsendvoucherbyemail)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($requestsendvoucherbyemail));
            } else {
                $httpBody = $requestsendvoucherbyemail;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendVoucherBySMS
     *
     * Send voucher by sms
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYSMS $requestsendvoucherbysms requestsendvoucherbysms (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherBySMS'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR
     */
    public function sendVoucherBySMS($x_gi_authorization, $requestsendvoucherbysms, string $contentType = self::contentTypes['sendVoucherBySMS'][0])
    {
        list($response) = $this->sendVoucherBySMSWithHttpInfo($x_gi_authorization, $requestsendvoucherbysms, $contentType);
        return $response;
    }

    /**
     * Operation sendVoucherBySMSWithHttpInfo
     *
     * Send voucher by sms
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYSMS $requestsendvoucherbysms (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherBySMS'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendVoucherBySMSWithHttpInfo($x_gi_authorization, $requestsendvoucherbysms, string $contentType = self::contentTypes['sendVoucherBySMS'][0])
    {
        $request = $this->sendVoucherBySMSRequest($x_gi_authorization, $requestsendvoucherbysms, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\HTTPBADREQUEST' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPBADREQUEST' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPBADREQUEST', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPUNAUTHORIZED', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\HTTPNOTFOUND' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPNOTFOUND' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPNOTFOUND', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPBADREQUEST',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPUNAUTHORIZED',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPNOTFOUND',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendVoucherBySMSAsync
     *
     * Send voucher by sms
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYSMS $requestsendvoucherbysms (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherBySMS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoucherBySMSAsync($x_gi_authorization, $requestsendvoucherbysms, string $contentType = self::contentTypes['sendVoucherBySMS'][0])
    {
        return $this->sendVoucherBySMSAsyncWithHttpInfo($x_gi_authorization, $requestsendvoucherbysms, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendVoucherBySMSAsyncWithHttpInfo
     *
     * Send voucher by sms
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYSMS $requestsendvoucherbysms (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherBySMS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoucherBySMSAsyncWithHttpInfo($x_gi_authorization, $requestsendvoucherbysms, string $contentType = self::contentTypes['sendVoucherBySMS'][0])
    {
        $returnType = '\OpenAPI\Client\Model\VOUCHERSENDSMSRESPONSE';
        $request = $this->sendVoucherBySMSRequest($x_gi_authorization, $requestsendvoucherbysms, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendVoucherBySMS'
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYSMS $requestsendvoucherbysms (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherBySMS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendVoucherBySMSRequest($x_gi_authorization, $requestsendvoucherbysms, string $contentType = self::contentTypes['sendVoucherBySMS'][0])
    {

        // verify the required parameter 'x_gi_authorization' is set
        if ($x_gi_authorization === null || (is_array($x_gi_authorization) && count($x_gi_authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_gi_authorization when calling sendVoucherBySMS'
            );
        }

        // verify the required parameter 'requestsendvoucherbysms' is set
        if ($requestsendvoucherbysms === null || (is_array($requestsendvoucherbysms) && count($requestsendvoucherbysms) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $requestsendvoucherbysms when calling sendVoucherBySMS'
            );
        }


        $resourcePath = '/api/v4.0/vouchers/send/sms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_gi_authorization !== null) {
            $headerParams['X-GI-Authorization'] = ObjectSerializer::toHeaderValue($x_gi_authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($requestsendvoucherbysms)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($requestsendvoucherbysms));
            } else {
                $httpBody = $requestsendvoucherbysms;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendVoucherByZNS
     *
     * Send voucher by zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYZNS|null $requestsendvoucherbyzns requestsendvoucherbyzns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByZNS'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR
     */
    public function sendVoucherByZNS($x_gi_authorization, $requestsendvoucherbyzns = null, string $contentType = self::contentTypes['sendVoucherByZNS'][0])
    {
        list($response) = $this->sendVoucherByZNSWithHttpInfo($x_gi_authorization, $requestsendvoucherbyzns, $contentType);
        return $response;
    }

    /**
     * Operation sendVoucherByZNSWithHttpInfo
     *
     * Send voucher by zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYZNS|null $requestsendvoucherbyzns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByZNS'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE|\OpenAPI\Client\Model\HTTPBADREQUEST|\OpenAPI\Client\Model\HTTPUNAUTHORIZED|\OpenAPI\Client\Model\HTTPNOTFOUND|\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendVoucherByZNSWithHttpInfo($x_gi_authorization, $requestsendvoucherbyzns = null, string $contentType = self::contentTypes['sendVoucherByZNS'][0])
    {
        $request = $this->sendVoucherByZNSRequest($x_gi_authorization, $requestsendvoucherbyzns, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\HTTPBADREQUEST' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPBADREQUEST' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPBADREQUEST', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPUNAUTHORIZED' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPUNAUTHORIZED', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\HTTPNOTFOUND' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPNOTFOUND' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPNOTFOUND', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPBADREQUEST',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPUNAUTHORIZED',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPNOTFOUND',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPINTERNALSERVERERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendVoucherByZNSAsync
     *
     * Send voucher by zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYZNS|null $requestsendvoucherbyzns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByZNS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoucherByZNSAsync($x_gi_authorization, $requestsendvoucherbyzns = null, string $contentType = self::contentTypes['sendVoucherByZNS'][0])
    {
        return $this->sendVoucherByZNSAsyncWithHttpInfo($x_gi_authorization, $requestsendvoucherbyzns, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendVoucherByZNSAsyncWithHttpInfo
     *
     * Send voucher by zns
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYZNS|null $requestsendvoucherbyzns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByZNS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoucherByZNSAsyncWithHttpInfo($x_gi_authorization, $requestsendvoucherbyzns = null, string $contentType = self::contentTypes['sendVoucherByZNS'][0])
    {
        $returnType = '\OpenAPI\Client\Model\VOUCHERSENDZNSRESPONSE';
        $request = $this->sendVoucherByZNSRequest($x_gi_authorization, $requestsendvoucherbyzns, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendVoucherByZNS'
     *
     * @param  string $x_gi_authorization Authorization (required)
     * @param  \OpenAPI\Client\Model\REQUESTSENDVOUCHERBYZNS|null $requestsendvoucherbyzns (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoucherByZNS'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendVoucherByZNSRequest($x_gi_authorization, $requestsendvoucherbyzns = null, string $contentType = self::contentTypes['sendVoucherByZNS'][0])
    {

        // verify the required parameter 'x_gi_authorization' is set
        if ($x_gi_authorization === null || (is_array($x_gi_authorization) && count($x_gi_authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_gi_authorization when calling sendVoucherByZNS'
            );
        }



        $resourcePath = '/api/v4.0/vouchers/send/zns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_gi_authorization !== null) {
            $headerParams['X-GI-Authorization'] = ObjectSerializer::toHeaderValue($x_gi_authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($requestsendvoucherbyzns)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($requestsendvoucherbyzns));
            } else {
                $httpBody = $requestsendvoucherbyzns;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
